{
 "title": "Gitlab K8s Runners - Used resources per job",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "NAMESPACE", "query": { "query": "label_values(namespace)" } },
   { "name": "project_name", "label": "project_name", "query": ".*" },
   { "name": "job_name", "label": "job_name", "query": ".*" },
   { "name": "job_id", "label": "job_id", "query": ".*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# How to use this dashboard?\n\nBy default this dashboard shows stats\nabout all the GitLab jobs running\nin the K8s runner. `project_name`, `job_name` and \n`job_id` are regexes, meaning that if you \nwant to get stats for all the projects in a group\nyou can type `group/.*` in the `project_name`\nfield. If you just want to see stats\nfor a specific job, just use the `job_id` \nfield."
   },
   "targets": [
    {}
   ]
  },
  { "title": "Used resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(rate(container_cpu_usage_seconds_total{namespace=\"$NAMESPACE\",pod=~\"runner.*\", container=\"build\"}[$__rate_interval])) + on (pod) group_left (annotation_gitlab_job_id, annotation_gitlab_project_path, annotation_gitlab_job_name) (0 * kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"})",
     "legendFormat": "{{annotation_gitlab_project_path}} - {{annotation_gitlab_job_name}}:{{annotation_gitlab_job_id}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{namespace=\"$NAMESPACE\",pod=~\"runner.*\", container=\"build\"}) + on (pod) group_left (annotation_gitlab_job_id, annotation_gitlab_project_path, annotation_gitlab_job_name) (0 * kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"})\n",
     "legendFormat": "{{annotation_gitlab_project_path}} - {{annotation_gitlab_job_name}}:{{annotation_gitlab_job_id}}"
    }
   ]
  },
  {
   "title": "Network bytes received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(rate(container_network_receive_bytes_total{namespace=\"$NAMESPACE\",pod=~\"runner.*\",id!~\"/system.slice.*\"}[$__rate_interval])) + on (pod) group_left (annotation_gitlab_job_id, annotation_gitlab_project_path, annotation_gitlab_job_name) (0 * kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"})",
     "legendFormat": "{{annotation_gitlab_project_path}} - {{annotation_gitlab_job_name}}:{{annotation_gitlab_job_id}}"
    }
   ]
  },
  {
   "title": "Network bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(rate(container_network_transmit_bytes_total{namespace=\"$NAMESPACE\",pod=~\"runner.*\",id!~\"/system.slice.*\"}[$__rate_interval])) + on (pod) group_left (annotation_gitlab_job_id, annotation_gitlab_project_path, annotation_gitlab_job_name) (0 * kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"})",
     "legendFormat": "{{annotation_gitlab_project_path}} - {{annotation_gitlab_job_name}}:{{annotation_gitlab_job_id}}"
    }
   ]
  },
  {
   "title": "Disk read bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_fs_reads_bytes_total{namespace=\"$NAMESPACE\", pod=~\"runner-.*\", container=\"build\"}[$__rate_interval])) + on (pod) group_left (annotation_gitlab_job_id, annotation_gitlab_project_path, annotation_gitlab_job_name) (0 * kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"})",
     "legendFormat": "{{annotation_gitlab_project_path}} - {{annotation_gitlab_job_name}}:{{annotation_gitlab_job_id}}"
    }
   ]
  },
  {
   "title": "Disk write bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_fs_writes_bytes_total{pod=~\"runner-.*\", container=\"build\"}[$__rate_interval])) + on (pod) group_left (annotation_gitlab_job_id, annotation_gitlab_project_path, annotation_gitlab_job_name) (0 * kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"})",
     "legendFormat": "{{annotation_gitlab_project_path}} - {{annotation_gitlab_job_name}}:{{annotation_gitlab_job_id}}"
    }
   ]
  },
  {
   "title": "Max used cores",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(rate(container_cpu_usage_seconds_total{namespace=\"$NAMESPACE\",pod=~\"runner.*\", container=\"build\"}[$__rate_interval])) + on (pod) group_left (annotation_gitlab_job_id, annotation_gitlab_project_path, annotation_gitlab_job_name) (0 * kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"})\n",
     "legendFormat": "{{annotation_gitlab_project_path}} - {{annotation_gitlab_job_name}}:{{annotation_gitlab_job_id}}"
    }
   ]
  },
  {
   "title": "Max used RAM",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{namespace=\"$NAMESPACE\",pod=~\"runner.*\",container=\"build\"}) + on (pod) group_left (annotation_gitlab_job_id, annotation_gitlab_project_path, annotation_gitlab_job_name) (0 * kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"})\n",
     "legendFormat": "{{annotation_gitlab_project_path}} - {{annotation_gitlab_job_name}}:{{annotation_gitlab_job_id}}"
    }
   ]
  },
  {
   "title": "Concurrent jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "count(kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"}) OR on() vector(0)"
    },
    { "expr": "gitlab_runner_concurrent" }
   ]
  },
  { "title": "Kubernetes requests/limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Stacked CPU Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$NAMESPACE\",pod=~\"runner.*\",resource=\"cpu\",container=\"build\"} + on (pod) group_left (annotation_gitlab_job_id, annotation_gitlab_project_path, annotation_gitlab_job_name) (0 * kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"})",
     "legendFormat": "{{annotation_gitlab_project_path}} - {{annotation_gitlab_job_name}}:{{annotation_gitlab_job_id}}"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$NAMESPACE\",resource=\"limits.cpu\",type=\"hard\"}",
     "legendFormat": "Quota limit"
    }
   ]
  },
  {
   "title": "Stacked CPU Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$NAMESPACE\",pod=~\"runner.*\",resource=\"cpu\",container=\"build\"} + on (pod) group_left (annotation_gitlab_job_id, annotation_gitlab_project_path, annotation_gitlab_job_name) (0 * kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"})",
     "legendFormat": "{{annotation_gitlab_project_path}} - {{annotation_gitlab_job_name}}:{{annotation_gitlab_job_id}}"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$NAMESPACE\",resource=\"requests.cpu\",type=\"hard\"}",
     "legendFormat": "Quota limit"
    }
   ]
  },
  {
   "title": "Stacked Memory Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$NAMESPACE\",pod=~\"runner.*\",resource=\"memory\",container=\"build\"} + on (pod) group_left (annotation_gitlab_job_id, annotation_gitlab_project_path, annotation_gitlab_job_name) (0 * kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"})",
     "legendFormat": "{{annotation_gitlab_project_path}} - {{annotation_gitlab_job_name}}:{{annotation_gitlab_job_id}}"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$NAMESPACE\",resource=\"limits.memory\",type=\"hard\"}",
     "legendFormat": "Quota limit"
    }
   ]
  },
  {
   "title": "Stacked Memory Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$NAMESPACE\",pod=~\"runner.*\",resource=\"memory\",container=\"build\"} + on (pod) group_left (annotation_gitlab_job_id, annotation_gitlab_project_path, annotation_gitlab_job_name) (0 * kube_pod_annotations{pod=~\"runner.*\", annotation_gitlab_project_path=~\"$project_name\", annotation_gitlab_job_id=~\"$job_id\", annotation_gitlab_job_name=~\"$job_name\"})",
     "legendFormat": "{{annotation_gitlab_project_path}} - {{annotation_gitlab_job_name}}:{{annotation_gitlab_job_id}}"
    },
    {
     "expr": "kube_resourcequota{namespace=\"$NAMESPACE\",resource=\"requests.memory\",type=\"hard\"}",
     "legendFormat": "Quota limit"
    }
   ]
  }
 ]
}